"""Ajout du champ title à la table conversations

Revision ID: 6357e7414752
Revises: 90f2358616db
Create Date: 2025-04-10 17:57:53.818629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6357e7414752'
down_revision: Union[str, None] = '90f2358616db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('title', sa.String(), nullable=True))
    op.create_index(op.f('ix_conversations_title'), 'conversations', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_title'), table_name='conversations')
    op.drop_column('conversations', 'title')
    # ### end Alembic commands ###
