"""add category to conversation

Revision ID: 90f2358616db
Revises: 41194a040fff
Create Date: 2025-04-09 15:34:54.438230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f2358616db'
down_revision: Union[str, None] = '41194a040fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('category', sa.String(), nullable=True))
    op.create_index(op.f('ix_conversations_category'), 'conversations', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_category'), table_name='conversations')
    op.drop_column('conversations', 'category')
    # ### end Alembic commands ###
